sources:
    - url: https://gist.github.com/ResistanceIsUseless/e46848f67706a8aa1205c9d2866bff31
    - url: https://github.com/0x71rex/0-Nuclei-Templates
    - url: https://github.com/0x71rex/0-fuzzing-templates
    - url: https://github.com/0x727/ObserverWard
    - url: https://github.com/0x727/ObserverWard_0x727
    - url: https://github.com/0xAwali/Blind-SSRF
    - url: https://github.com/0xAwali/Virtual-Host
    - url: https://github.com/0xElkot/My-Nuclei-Templates
    - url: https://github.com/0xKayala/Custom-Nuclei-Templates
    - url: https://github.com/0xPugazh/my-nuclei-templates
    - url: https://github.com/0xc4sper0/Nuclei-templates
    - url: https://github.com/0xmaximus/final_freaking_nuclei_templates
    - url: https://github.com/1in9e/my-nuclei-templates
    - url: https://github.com/20142995/nuclei-templates
    - url: https://github.com/5cr1pt/templates
    - url: https://github.com/ARPSyndicate/kenzer-templates
    - url: https://github.com/Akokonunes/Private-Nuclei-Templates
    - url: https://github.com/Arvinthksrct/alltemplate
    - url: https://github.com/AshiqurEmon/nuclei_templates
    - url: https://github.com/BagheeraAltered/FuzzingTemplate
    - url: https://github.com/Caddyshack2175/nuclei-custom-templates
    - url: https://github.com/CharanRayudu/Custom-Nuclei-Templates
    - url: https://github.com/Christbowel/CVE-2024-25600_Nuclei-Template
    - url: https://github.com/Co5mos/nuclei-tps
    - url: https://github.com/Dalaho-bangin/my_nuclei_templates
    - url: https://github.com/DoubleTakes/nuclei-templates
    - url: https://github.com/Elsfa7-110/mynuclei-templates
    - url: https://github.com/EslamMonex/subdomain-takeover
    - url: https://github.com/Excis3/bans4-nuclei
    - url: https://github.com/ExpLangcn/NucleiTP
    - url: https://github.com/GhostTroops/scan4all
    - url: https://github.com/Harish4948/Nuclei-Templates
    - url: https://github.com/HernanRodriguez1/ScanReflectedSSTI
    - url: https://github.com/HuTa0kj/NucleiManual
    - url: https://github.com/Hunt2behunter/nuclei-templates
    - url: https://github.com/Jagomeiister/nuclei-templates
    - url: https://github.com/JohnDoeAnonITA/NucleiTemplatePRV
    - url: https://github.com/JoshMorrison99/my-nuceli-templates
    - url: https://github.com/JoshMorrison99/url-based-nuclei-templates
    - url: https://github.com/Kaue-Navarro/Templates-kaue-nuclei
    - url: https://github.com/KeepHowling/all_freaking_nuclei_templates
    - url: https://github.com/Lopseg/nuclei-c-templates
    - url: https://github.com/Lu3ky13/Authorization-Nuclei-Templates
    - url: https://github.com/MR-pentestGuy/nuclei-templates
    - url: https://github.com/Mr-xn/CVE-2023-23333
    - url: https://github.com/NightRang3r/misc_nuclei_templates
    - url: https://github.com/NitinYadav00/My-Nuclei-Templates
    - url: https://github.com/NoRed0x/nored0x-Nuclei-Templates
    - url: https://github.com/Odayex/Random-Nuclei-Templates
    - url: https://github.com/PedroF-369/nuclei_templates
    - url: https://github.com/PedroFerreira97/nuclei_templates
    - url: https://github.com/R-s0n/Custom_Vuln_Scan_Templates
    - url: https://github.com/RandomRobbieBF/nuclei-drupal-sa
    - url: https://github.com/Red-Darkin/Custom-Nuclei-Templates
    - url: https://github.com/Saimonkabir/Nuclei-Templates
    - url: https://github.com/Saptak9983/Nuclei-Template
    - url: https://github.com/Shakilll/my_nuclei_templates
    - url: https://github.com/SirAppSec/nuclei-template-generator-log4j
    - url: https://github.com/SirBugs/Priv8-Nuclei-Templates
    - url: https://github.com/Str1am/my-nuclei-templates
    - url: https://github.com/SumedhDawadi/Custom-Nuclei-Template
    - url: https://github.com/System00-Security/backflow
    - url: https://github.com/U53RW4R3/nuclei-fuzzer-templates
    - url: https://github.com/UltimateSec/ultimaste-nuclei-templates
    - url: https://github.com/VulnExpo/nuclei-templates
    - url: https://github.com/YuanBenSir/Nuclei_poc_C
    - url: https://github.com/adampielak/nuclei-templates
    - url: https://github.com/adysec/nuclei_poc
    - url: https://github.com/aels/CVE-2022-37042
    - url: https://github.com/al00000000al/my_nuclei_templates
    - url: https://github.com/alexrydzak/rydzak-nuclei-templates
    - url: https://github.com/atk7r/Nuclei-Poc
    - url: https://github.com/ayadim/Nuclei-bug-hunter
    - url: https://github.com/badboy-sft/badboy_17-Nuclei-Templates-Collection
    - url: https://github.com/badboycxcc/CVE-2023-24100
    - url: https://github.com/bhataasim1/PersonalTemplates
    - url: https://github.com/binod235/nuclei-templates-and-reports
    - url: https://github.com/blazeinfosec/nuclei-templates
    - url: https://github.com/bmjoker/Nuclei2use
    - url: https://github.com/boobooHQ/private_templates
    - url: https://github.com/brinhosa/brinhosa-nuclei-templates
    - url: https://github.com/bug-vs-me/nuclei
    - url: https://github.com/c-sh0/nuclei_templates
    - url: https://github.com/charonlight/pocs
    - url: https://github.com/cipher387/juicyinfo-nuclei-templates
    - url: https://github.com/clarkvoss/Nuclei-Templates
    - url: https://github.com/coldrainh/nuclei-ByMyself
    - url: https://github.com/d3sca/Nuclei_Templates
    - url: https://github.com/daffainfo/my-nuclei-templates
    - url: https://github.com/damon-sec/Nuclei-templates-Collection
    - url: https://github.com/damon-sec/TCSZ-Nuclei
    - url: https://github.com/davidfortytwo/GetNucleiTemplates
    - url: https://github.com/dioos886/Nuclei-POC
    - url: https://github.com/dk4trin/templates-nuclei
    - url: https://github.com/ed-red/redmc_custom_templates_nuclei
    - url: https://github.com/edoardottt/missing-cve-nuclei-templates
    - url: https://github.com/ekinsb/Nuclei-Templates
    - url: https://github.com/erickfernandox/nuclei-templates
    - url: https://github.com/esetal/nuclei-bb-templates
    - url: https://github.com/ethicalhackingplayground/erebus-templates
    - url: https://github.com/freakyclown/Nuclei_templates
    - url: https://github.com/geeknik/nuclei-templates-1
    - url: https://github.com/geeknik/the-nuclei-templates
    - url: https://github.com/glyptho/templatesallnuclei
    - url: https://github.com/h0tak88r/nuclei_templates
    - url: https://github.com/h4ndsh/nuclei-templates
    - url: https://github.com/hughink/nuclei-poc
    - url: https://github.com/iamHuFei/HVVault
    - url: https://github.com/im403/nuclei-temp
    - url: https://github.com/imhunterand/nuclei-custom-templates
    - url: https://github.com/javaongsan/nuclei-templates
    - url: https://github.com/jiankeguyue/nuclei_pocs
    - url: https://github.com/justmumu/SpringShell
    - url: https://github.com/kabilan1290/templates
    - url: https://github.com/kh4sh3i/CVE-2022-23131
    - url: https://github.com/kh4sh3i/Webmin-CVE
    - url: https://github.com/l1b3ri/nuclei-poc
    - url: https://github.com/luck-ying/Library-YAML-POC
    - url: https://github.com/madisec/nuclei-templates
    - url: https://github.com/mastersir-lab/nuclei-yaml-poc
    - url: https://github.com/mbskter/Masscan2Httpx2Nuclei-Xray
    - url: https://github.com/mdsabbirkhan/0xPugazh-my-nuclei-templates
    - url: https://github.com/medbsq/ncl
    - url: https://github.com/meme-lord/Custom-Nuclei-Templates
    - url: https://github.com/microphone-mathematics/custom-nuclei-templates
    - url: https://github.com/n1f2c3/mytemplates
    - url: https://github.com/notnotnotveg/nuclei-custom-templates
    - url: https://github.com/nvsecurity/nightvision-nuclei-templates
    - url: https://github.com/obreinx/nuceli-templates
    - url: https://github.com/optiv/mobile-nuclei-templates
    - url: https://github.com/panch0r3d/nuclei-templates
    - url: https://github.com/peanuth8r/Nuclei_Templates
    - url: https://github.com/pentest-dev/Profesional-Nuclei-Templates
    - url: https://github.com/pikpikcu/my-nuclei-templates
    - url: https://github.com/pikpikcu/nuclei-fuzz
    - url: https://github.com/pikpikcu/nuclei-templates
    - url: https://github.com/ping-0day/templates
    - url: https://github.com/praetorian-inc/chariot-launch-nuclei-templates
    - url: https://github.com/praetorian-inc/zeroqlik-detect
    - url: https://github.com/projectdiscovery/nuclei-templates
      official: true
    - url: https://github.com/ptyspawnbinbash/template-enhancer
    - url: https://github.com/qaisarafridi/MY-Nuclei-Templates
    - url: https://github.com/r3dcl1ff/Symfony-Fuck
    - url: https://github.com/rafaelcaria/Nuclei-Templates
    - url: https://github.com/rafaelwdornelas/my-nuclei-templates
    - url: https://github.com/rahulkadavil/nuclei-templates
    - url: https://github.com/rainnull/nuclei-poc
    - url: https://github.com/randomstr1ng/nuclei-sap-templates
    - url: https://github.com/redteambrasil/nuclei-templates
    - url: https://github.com/ree4pwn/my-nuclei-templates
    - url: https://github.com/reewardius/interested-nuclei-templates
    - url: https://github.com/reewardius/log4shell-templates
    - url: https://github.com/rhbb/nuclei-poc
    - url: https://github.com/ricardomaia/nuclei-template-generator-for-wordpress-plugins
    - url: https://github.com/rix4uni/BugBountyTips
    - url: https://github.com/rum3ch/Ae86
    - url: https://github.com/rxerium/CISA-KEV
    - url: https://github.com/sadnansakin/my-nuclei-templates
    - url: https://github.com/securitytest3r/nuclei_templates_work
    - url: https://github.com/sharathkramadas/k8s-nuclei-templates
    - url: https://github.com/shifa123/detections
    - url: https://github.com/sl4x0/NC-Templates
    - url: https://github.com/smaranchand/nuclei-templates
    - url: https://github.com/solo10010/solo-nuclei-templates
    - url: https://github.com/soumya123raj/Nuclei
    - url: https://github.com/srkgupta/cent-nuclei-templates
    - url: https://github.com/tamimhasan404/Open-Source-Nuclei-Templates-Downloader
    - url: https://github.com/test502git/log4j-fuzz-head-poc
    - url: https://github.com/th3r4id/nuclei-templates
    - url: https://github.com/thanhnx9/nuclei-templates-cutomer
    - url: https://github.com/thebrnwal/Content-Injection-Nuclei-Script
    - url: https://github.com/thecyberneh/nuclei-templatess
    - url: https://github.com/thelabda/nuclei-templates
    - url: https://github.com/themoonbaba/private_templates
    - url: https://github.com/tomilgxa/nuclei-poc
    - url: https://github.com/topscoder/nuclei-wordfence-cve
    - url: https://github.com/topscoder/nuclei-zero-day
    - url: https://github.com/toramanemre/apache-solr-log4j-CVE-2021-44228
    - url: https://github.com/toramanemre/log4j-rce-detect-waf-bypass
    - url: https://github.com/trickest/log4j
    - url: https://github.com/umityn/my-nuclei-templates
    - url: https://github.com/v3l4r10/Nuclei-Templates
    - url: https://github.com/valaDevs/nuclei-backupfile-finder
    - url: https://github.com/vijay922/XXE-FUZZ
    - url: https://github.com/vulnspace/nuclei-templates
    - url: https://github.com/wasp76b/nuclei-templates
    - url: https://github.com/wearetyomsmnv/llm_integrated_nuclei_templates
    - url: https://github.com/wjlin0/nuclei-poc
    - url: https://github.com/wr00t/templates
    - url: https://github.com/xinZa1/template
    - url: https://github.com/yarovit-developer/nuclei-templates
    - url: https://github.com/yavolo/nuclei-templates
    - url: https://github.com/z3bd/nuclei-templates
    - url: https://github.com/zer0yu/Open-PoC
    - url: https://github.com/zerbaliy3v/custom-nuclei-templates
    - url: https://github.com/zodmagus/z0ds3c-Nuclei-Templates
